# Generated by Django 2.2.4 on 2019-08-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='outPass',
            fields=[
                ('outpassId', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('whatsappImg', models.FileField(blank=True, null=True, upload_to='Whatsapp ScreenShots')),
                ('outPassDate', models.DateTimeField()),
                ('matter', models.TextField()),
                ('approved_by_parent', models.BooleanField(default=False)),
                ('approved_by_warden', models.BooleanField(default=False)),
                ('isEmergency', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonPanel.UserDetails')),
            ],
        ),
    ]
