# Generated by Django 2.2.4 on 2019-08-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonPanel', '0001_initial'),
        ('student', '0002_auto_20190814_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredColleges',
            fields=[
                ('collegeId', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=200)),
                ('shortHand', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.URLField(max_length=100)),
                ('contact_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('er_no', models.CharField(max_length=7)),
                ('year', models.PositiveIntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('hostel', models.CharField(max_length=50)),
                ('room_no', models.CharField(max_length=50)),
                ('bed_no', models.PositiveIntegerField()),
                ('isVerfified', models.BooleanField(default=False)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.RegisteredColleges')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='commonPanel.UserDetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonPanel.UserDetails')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warden', to='commonPanel.UserDetails')),
            ],
        ),
    ]
