# Generated by Django 2.2.4 on 2019-08-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190815_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='warden',
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of_student', to='parents.Parent'),
        ),
    ]
