# Generated by Django 2.2.4 on 2019-08-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='type',
            new_name='typeOfRequest',
        ),
        migrations.AddField(
            model_name='requests',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
