# Generated by Django 2.2.4 on 2019-08-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20190816_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver1', to='commonPanel.UserDetails'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender1', to='commonPanel.UserDetails'),
        ),
    ]
