# Generated by Django 2.2.4 on 2019-08-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20190816_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='commonPanel.UserDetails'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='commonPanel.UserDetails'),
        ),
    ]
