# Generated by Django 2.2.4 on 2019-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20190816_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='Signatures'),
        ),
    ]
