# Generated by Django 2.2.4 on 2019-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_student_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
