# Generated by Django 2.2.4 on 2019-08-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20190816_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcolleges',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
