# Generated by Django 2.2.4 on 2019-08-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_registeredcolleges_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
