# Generated by Django 2.2.4 on 2019-08-19 17:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_student_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpass',
            name='approved_by_parent',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Parent's Contact phone number", max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
