# Generated by Django 2.2.4 on 2019-08-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_requests_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='receiver',
        ),
    ]
