# Generated by Django 2.2.4 on 2019-08-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_remove_requests_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpass',
            name='fromDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outpass',
            name='toDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
