# Generated by Django 2.2.4 on 2019-08-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_outpass_generated_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='uniqueHash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
