# Generated by Django 2.2.4 on 2019-08-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_outpass_uniquehash'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='mark_as_read',
            field=models.BooleanField(default=False),
        ),
    ]
