# Generated by Django 2.2.4 on 2019-08-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0002_warden_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warden',
            name='hostels',
        ),
        migrations.AddField(
            model_name='warden',
            name='hostel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
