# Generated by Django 2.2.4 on 2019-08-20 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0003_auto_20190820_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warden',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.RegisteredColleges'),
        ),
    ]
