# Generated by Django 2.2.4 on 2019-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0004_auto_20190820_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warden',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='warden',
            name='er_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
