# Generated by Django 2.2.4 on 2019-08-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0005_auto_20190821_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='Warden Id'),
        ),
    ]
