# Generated by Django 2.2.4 on 2019-08-30 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_outpass_mark_as_read'),
        ('warden', '0008_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='outpass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.outPass'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
