# Generated by Django 2.2.4 on 2019-08-30 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_outpass_mark_as_read'),
        ('warden', '0009_auto_20190831_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.RegisteredColleges'),
        ),
    ]
