# Generated by Django 2.2.4 on 2019-08-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0010_notifications_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
