# Generated by Django 2.2.4 on 2019-08-14 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('phone1', models.CharField(blank=True, max_length=14, null=True)),
                ('country', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(default=None, max_length=100)),
                ('state', models.CharField(default=None, max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='profile_pictures')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
