# Generated by Django 2.2.4 on 2019-08-18 12:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('commonPanel', '0004_auto_20190815_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='parent_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Parent's Contact phone number", max_length=128, null=True, region=None),
        ),
    ]
