# Generated by Django 2.2.4 on 2019-08-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonPanel', '0005_auto_20190818_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='parent_contact',
        ),
    ]
